# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai-workshops',
                'doc_host': 'https://sudolabs-io.github.io',
                'git_url': 'https://github.com/sudolabs-io/ai-workshops',
                'lib_path': 'ai_workshops'},
  'syms': {'ai_workshops.core': {'ai_workshops.core.foo': ('core.html#foo', 'ai_workshops/core.py')}}}
